import './get-config';
import './get-directions';
import './get-directions-except-many';
import './get-directions-except-one';
import './get-distance';
import './get-inverse-direction';
import './get-random-direction';
import './get-random-value';
import './move-individual';
